### ISSUE TITLE
data.target points to the wrong DOM object

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/brisky-events#21]
In scroll listener, `data` is the first parameter. When we use it to the object, and we scroll inside, `data.target` should give us DOM node we mouse over and not the DOM node we listen to.

**Comment by nikoloza** [comment]
I think `this.node` or `this.target` should be giving this DOM node, as we had before.

**Comment by nikoloza** [comment]
I'm not sure if this is right, I've just checked native event listener, which does the same, would be nice tho :)

**Comment by youzi** [comment]
This is not how event listeners work. If you need the hovered element you can use getElementByPoint
