### ISSUE TITLE
[bug] strange behavior on search background when clicking

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/brisky-events#4]
I have a case when:
- `click` does not work
- `down` works
- but it triggers element which is below actual element you click (no `pointer-events` or something applied).

So, it happens when you want to close `search` on clicking on background. Now I do just a quick trick to make it working, but when we have time, it worth to check.

example code here: https://github.com/vigour-io/play-search/blob/fa18ac824572ba8edba3f23c006e7610b580dbfb/lib/index.js#L143-L154

**Comment by jimdebeer** [comment]
nothing to do with event, was the storeState: true prop see #6
